version: '3'
services:
  db-sbk-api:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432 # внешний порт контейнера : стандартный внутренний порт контейнера PostgreSQL
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_sbk #название_БД, которая будет создана в PostreSQL контейнера
